# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190512_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=2, verbose_name='性别'),
        ),
    ]
